### ISSUE TITLE
How does the accuracy of the WhisperJAV model compare to uncustomized faster-whisper-large-v3-turbo?

### ISSUE THREAD

**Issue by JasonxlxCharles** [meizhong986/WhisperJAV#11]
First, thank you for your dedication and contributions!

However, with the release of faster-whisper-large-v3-turbo, numerous customized Whisper models have implemented improvements, while WhisperJAV's latest model version remains at large-v2.

I understand that you might not have updated to large-v3-turbo due to time constraints or other considerations. I would like to know which model demonstrates superior speech recognition accuracy for JAV content - WhisperJAV or the uncustomized faster-whisper-large-v3-turbo?

Thank you very much.

**Comment by meizhong986** [comment]
By customised do you mean retrained / fine-tuned models based on v3? If you
have any in mind just send me the links and I can look into them.

For JAV, the large-v3 model and the large-v3-turbo both underperform
large-v2. Even large-v1 performs better than v3 for JAV.
V3 does perform better for podcasts and clear studio grade audios.
