### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Pochoxo** [meizhong986/WhisperJAV#6]
Hello, first off, thank you for all of the work you've put into this!  I use it a couple of times a week and it's been an awesome tool!  Starting tonight, i'm getting an error and i'm guessing it's an update issue.  Thank you very much!

Here's the error text:
WARNING:faster_whisper:An error occured while synchronizing the model Systran/faster-whisper-large-v2 from the Hugging Face Hub:
An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
WARNING:faster_whisper:Trying to load the model directly from the local cache, if it exists.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    285     try:
--> 286         response.raise_for_status()
    287     except HTTPError as e:

14 frames
HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/api/models/Systran/faster-whisper-large-v2/revision/main

The above exception was the direct cause of the following exception:

HfHubHTTPError                            Traceback (most recent call last)
HfHubHTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/api/models/Systran/faster-whisper-large-v2/revision/main

The above exception was the direct cause of the following exception:

LocalEntryNotFoundError                   Traceback (most recent call last)
LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

During handling of the above exception, another exception occurred:

LocalEntryNotFoundError                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/_snapshot_download.py](https://localhost:8080/#) in snapshot_download(repo_id, repo_type, revision, cache_dir, local_dir, local_dir_use_symlinks, library_name, library_version, user_agent, proxies, etag_timeout, resume_download, force_download, token, local_files_only, allow_patterns, ignore_patterns, max_workers, tqdm_class, endpoint)
    233         # If we couldn't find the appropriate folder on disk, raise an error.
    234         if local_files_only:
--> 235             raise LocalEntryNotFoundError(
    236                 "Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and "
    237                 "outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass "

LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.

**Comment by meizhong986** [comment]
Just saw this. Did the problem go away, or do you still get the error?

**Comment by Pochoxo** [comment]
I had the issue for a few days and then the issue just went away and it worked again. Not sure what happened but it's working for me so it's all good. Thank you for reaching out and checking!
