### ISSUE TITLE
Add .opus as acceptable audio file's extension

### ISSUE THREAD

**Issue by zealozb** [meizhong986/WhisperJAV#8]
Hi @meizhong986 , it'd be great if you can add `.opus` to the list of recognized audio extensions. Thanks!

**Comment by meizhong986** [comment]
Just added .opus.
Haven't tested it, give it a try, let me know if any breaks

**Comment by zealozb** [comment]
It works with no problem just like with the other audio formats. Thank you!

**Comment by zealozb** [comment]
I'm closing this issue
